name: mvc_demo
description: A new Flutter project.
version: 1.0.0+1
environment:
    sdk: ">=2.1.0 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    provider: ^4.0.4
    http: ^0.12.0+4
    smart_flare: ^0.2.8
    simple_animations: ^1.1.3
    page_transition: ^1.1.4
    transparent_image: ^1.0.0
    sqflite: ^1.2.2
    path_provider: ^1.6.5
dev_dependencies:
    flutter_launcher_icons: "^0.7.3"
    flutter_launcher_name: "^0.0.1"
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true
    assets:
        - assets/

flutter_launcher_name:
  name: "FlyBank"


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/flybank_logo.png"